### PR TITLE
readme: Update the needed PRs for Citra master

### PR DESCRIPTION
**Pull request by John-Gee**
Unless I am mistaken, canary is not required anymore.

Thank you!

### CODE REVIEW

**Comment by leoetlino** [comment]
Thanks for the PR. Any chance you could edit the readme to keep telling users to use a canary build and mention citra-emu/citra#4862 as the reason? That PR fixes another issue with Citra's patching support that might prevent Project Restoration from loading.

Also, please follow the existing message style for the commit message ("Do stuff" instead of "Stuff has been done" or "Does stuff").

**Comment by John-Gee** [comment]
Sure thing!

Is this better? Instead of adding the reason I thought it was cleaner to link to the PR.

**Comment by John-Gee** [comment]
Woooops sorry, I forgot the rename the PR :/

**Comment by leoetlino** [comment]
No worries. Thanks again for your contribution!

**Pull request merged**
